import { LayerVariableManager, VariableLayerInfo } from "./LayerVariableManager";

export class LayerVariableInfoManager {
  private static _instance: LayerVariableInfoManager | null = null;

  public variableLayerInfo: VariableLayerInfo = {
  "2:215": {
    "guid": "2:215",
    "childGuids": [
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:894",
      "2:904",
      "2:906",
      "2:905",
      "2:903",
      "2:898",
      "2:899",
      "2:897",
      "2:896",
      "2:895",
      "2:949",
      "2:947",
      "2:881",
      "2:891",
      "2:893",
      "2:892",
      "2:890",
      "2:885",
      "2:886",
      "2:884",
      "2:883",
      "2:882",
      "2:946",
      "2:944",
      "2:868",
      "2:878",
      "2:880",
      "2:879",
      "2:877",
      "2:872",
      "2:873",
      "2:871",
      "2:870",
      "2:869",
      "2:943",
      "2:941",
      "2:855",
      "2:865",
      "2:867",
      "2:866",
      "2:864",
      "2:859",
      "2:860",
      "2:858",
      "2:857",
      "2:856",
      "2:940",
      "2:938",
      "2:842",
      "2:852",
      "2:854",
      "2:853",
      "2:851",
      "2:846",
      "2:847",
      "2:845",
      "2:844",
      "2:843",
      "2:937",
      "2:935",
      "2:829",
      "2:839",
      "2:841",
      "2:840",
      "2:838",
      "2:833",
      "2:834",
      "2:832",
      "2:831",
      "2:830",
      "2:934",
      "2:932",
      "2:816",
      "2:826",
      "2:828",
      "2:827",
      "2:825",
      "2:820",
      "2:821",
      "2:819",
      "2:818",
      "2:817",
      "2:931",
      "2:929",
      "2:803",
      "2:813",
      "2:815",
      "2:814",
      "2:812",
      "2:807",
      "2:808",
      "2:806",
      "2:805",
      "2:804",
      "2:928",
      "2:926",
      "2:789",
      "2:800",
      "2:802",
      "2:801",
      "2:799",
      "2:794",
      "2:795",
      "2:793",
      "2:791",
      "2:267",
      "2:271",
      "2:272",
      "2:695",
      "2:702",
      "2:703",
      "2:696",
      "2:697",
      "2:701",
      "2:700",
      "2:699",
      "2:698",
      "2:268",
      "2:270",
      "2:269",
      "2:237",
      "2:264",
      "2:260",
      "2:261",
      "2:259",
      "2:253",
      "2:254",
      "2:249",
      "2:250",
      "2:243",
      "2:244",
      "2:248",
      "2:247",
      "2:246",
      "2:245",
      "2:238",
      "2:239",
      "2:216",
      "2:218",
      "2:230",
      "2:235",
      "2:234",
      "2:233",
      "2:232",
      "2:231",
      "2:225",
      "2:219",
      "2:217"
    ],
    "parentGuids": [
      "0:1"
    ],
    "colorValue": [
      {
        "varKey": "2:35",
        "varValue": "rgba(18, 11, 31, 1)"
      }
    ]
  },
  "2:217": {
    "guid": "2:217",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:216"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:235": {
    "guid": "2:235",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:216",
      "2:218",
      "2:230"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:237": {
    "guid": "2:237",
    "childGuids": [
      "2:264",
      "2:260",
      "2:261",
      "2:259",
      "2:253",
      "2:254",
      "2:249",
      "2:250",
      "2:243",
      "2:244",
      "2:248",
      "2:247",
      "2:246",
      "2:245",
      "2:238",
      "2:239"
    ],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236"
    ],
    "colorValue": [
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:238": {
    "guid": "2:238",
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:237"
    ],
    "childGuids": [
      "2:239"
    ],
    "floatValue": [
      {
        "varKey": "2:54",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:243": {
    "guid": "2:243",
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:237"
    ],
    "childGuids": [
      "2:244",
      "2:248",
      "2:247",
      "2:246",
      "2:245"
    ],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      }
    ]
  },
  "2:249": {
    "guid": "2:249",
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:237"
    ],
    "childGuids": [
      "2:250"
    ],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:253": {
    "guid": "2:253",
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:237"
    ],
    "childGuids": [
      "2:254"
    ],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:260": {
    "guid": "2:260",
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:237"
    ],
    "childGuids": [
      "2:261"
    ],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:266": {
    "guid": "2:266",
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265"
    ],
    "childGuids": [
      "2:707",
      "2:894",
      "2:904",
      "2:906",
      "2:905",
      "2:903",
      "2:898",
      "2:899",
      "2:897",
      "2:896",
      "2:895",
      "2:949",
      "2:947",
      "2:881",
      "2:891",
      "2:893",
      "2:892",
      "2:890",
      "2:885",
      "2:886",
      "2:884",
      "2:883",
      "2:882",
      "2:946",
      "2:944",
      "2:868",
      "2:878",
      "2:880",
      "2:879",
      "2:877",
      "2:872",
      "2:873",
      "2:871",
      "2:870",
      "2:869",
      "2:943",
      "2:941",
      "2:855",
      "2:865",
      "2:867",
      "2:866",
      "2:864",
      "2:859",
      "2:860",
      "2:858",
      "2:857",
      "2:856",
      "2:940",
      "2:938",
      "2:842",
      "2:852",
      "2:854",
      "2:853",
      "2:851",
      "2:846",
      "2:847",
      "2:845",
      "2:844",
      "2:843",
      "2:937",
      "2:935",
      "2:829",
      "2:839",
      "2:841",
      "2:840",
      "2:838",
      "2:833",
      "2:834",
      "2:832",
      "2:831",
      "2:830",
      "2:934",
      "2:932",
      "2:816",
      "2:826",
      "2:828",
      "2:827",
      "2:825",
      "2:820",
      "2:821",
      "2:819",
      "2:818",
      "2:817",
      "2:931",
      "2:929",
      "2:803",
      "2:813",
      "2:815",
      "2:814",
      "2:812",
      "2:807",
      "2:808",
      "2:806",
      "2:805",
      "2:804",
      "2:928",
      "2:926",
      "2:789",
      "2:800",
      "2:802",
      "2:801",
      "2:799",
      "2:794",
      "2:795",
      "2:793",
      "2:791",
      "2:267",
      "2:271",
      "2:272",
      "2:695",
      "2:702",
      "2:703",
      "2:696",
      "2:697",
      "2:701",
      "2:700",
      "2:699",
      "2:698",
      "2:268",
      "2:270",
      "2:269"
    ],
    "floatValue": [
      {
        "varKey": "2:52",
        "varValue": 24
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:37",
        "varValue": "rgba(22, 13, 38, 1)"
      }
    ]
  },
  "2:269": {
    "guid": "2:269",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:267",
      "2:268"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:270": {
    "guid": "2:270",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:267",
      "2:268"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:696": {
    "guid": "2:696",
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:267",
      "2:695"
    ],
    "childGuids": [
      "2:697",
      "2:701",
      "2:700",
      "2:699",
      "2:698"
    ],
    "floatValue": [
      {
        "varKey": "2:53",
        "varValue": 10
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      }
    ]
  },
  "2:698": {
    "guid": "2:698",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:267",
      "2:695",
      "2:696",
      "2:697"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:699": {
    "guid": "2:699",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:267",
      "2:695",
      "2:696",
      "2:697"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:700": {
    "guid": "2:700",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:267",
      "2:695",
      "2:696",
      "2:697"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:701": {
    "guid": "2:701",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:267",
      "2:695",
      "2:696",
      "2:697"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:702": {
    "guid": "2:702",
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:267",
      "2:695"
    ],
    "childGuids": [
      "2:703"
    ],
    "floatValue": [
      {
        "varKey": "2:53",
        "varValue": 10
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:39",
        "varValue": "rgba(44, 27, 77, 1)"
      }
    ]
  },
  "2:271": {
    "guid": "2:271",
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:267"
    ],
    "childGuids": [
      "2:272"
    ],
    "floatValue": [
      {
        "varKey": "2:53",
        "varValue": 10
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      }
    ]
  },
  "2:794": {
    "guid": "2:794",
    "childGuids": [
      "2:795"
    ],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:789"
    ],
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:801": {
    "guid": "2:801",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:789",
      "2:800"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:802": {
    "guid": "2:802",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:789",
      "2:800"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:805": {
    "guid": "2:805",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:803"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:807": {
    "guid": "2:807",
    "childGuids": [
      "2:808"
    ],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:803"
    ],
    "colorValue": [
      {
        "varKey": "2:46",
        "varValue": "rgba(124, 77, 255, 0.4)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:814": {
    "guid": "2:814",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:803",
      "2:813"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:815": {
    "guid": "2:815",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:803",
      "2:813"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:818": {
    "guid": "2:818",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:816"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:820": {
    "guid": "2:820",
    "childGuids": [
      "2:821"
    ],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:816"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:827": {
    "guid": "2:827",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:816",
      "2:826"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:828": {
    "guid": "2:828",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:816",
      "2:826"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:831": {
    "guid": "2:831",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:829"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:833": {
    "guid": "2:833",
    "childGuids": [
      "2:834"
    ],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:829"
    ],
    "colorValue": [
      {
        "varKey": "2:46",
        "varValue": "rgba(124, 77, 255, 0.4)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:840": {
    "guid": "2:840",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:829",
      "2:839"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:841": {
    "guid": "2:841",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:829",
      "2:839"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:844": {
    "guid": "2:844",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:842"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:846": {
    "guid": "2:846",
    "childGuids": [
      "2:847"
    ],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:842"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:853": {
    "guid": "2:853",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:842",
      "2:852"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:854": {
    "guid": "2:854",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:842",
      "2:852"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:855": {
    "guid": "2:855",
    "childGuids": [
      "2:865",
      "2:867",
      "2:866",
      "2:864",
      "2:859",
      "2:860",
      "2:858",
      "2:857",
      "2:856",
      "2:940",
      "2:938"
    ],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707"
    ],
    "colorValue": [
      {
        "varKey": "2:39",
        "varValue": "rgba(44, 27, 77, 1)"
      }
    ]
  },
  "2:857": {
    "guid": "2:857",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:855"
    ],
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      }
    ]
  },
  "2:859": {
    "guid": "2:859",
    "childGuids": [
      "2:860"
    ],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:855"
    ],
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:866": {
    "guid": "2:866",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:855",
      "2:865"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:867": {
    "guid": "2:867",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:855",
      "2:865"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:870": {
    "guid": "2:870",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:868"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:872": {
    "guid": "2:872",
    "childGuids": [
      "2:873"
    ],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:868"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:879": {
    "guid": "2:879",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:868",
      "2:878"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:880": {
    "guid": "2:880",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:868",
      "2:878"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:883": {
    "guid": "2:883",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:881"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:885": {
    "guid": "2:885",
    "childGuids": [
      "2:886"
    ],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:881"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:892": {
    "guid": "2:892",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:881",
      "2:891"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:893": {
    "guid": "2:893",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:881",
      "2:891"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:896": {
    "guid": "2:896",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:894"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:898": {
    "guid": "2:898",
    "childGuids": [
      "2:899"
    ],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:894"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:905": {
    "guid": "2:905",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:894",
      "2:904"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:906": {
    "guid": "2:906",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:215",
      "2:236",
      "2:265",
      "2:266",
      "2:707",
      "2:894",
      "2:904"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  }
};

  private constructor() {}


  static get instance(): LayerVariableInfoManager {
    if (!LayerVariableInfoManager._instance) {
      LayerVariableInfoManager._instance = new LayerVariableInfoManager();
    }
    return LayerVariableInfoManager._instance;
  }
  // 更新当前图层的模式设置
  // 更新后需要循环更新当前图层下子图层所有的变量模式
  updateSetToMode(guid: string, setId: string, modeId: string) {
    const variableLayer = this.variableLayerInfo[guid];
    if (!variableLayer) {
      return;
    }
    variableLayer.setToMode = {};
    variableLayer.setToMode[setId] = modeId;
    //开始更新所有包含子图层的数据信息
    const guids = [guid, ...variableLayer.childGuids];
    for (let item of guids) {
      const layer = this.variableLayerInfo[item];
      if (layer) {
        if (layer.colorValue) {
          for(let i = 0;i<layer.colorValue.length;i++){
            if(item!==guid && layer.setToMode) continue
            const returnValue = LayerVariableManager.instance.getColor(item, layer.colorValue[i].varKey)
            layer.colorValue[i].varValue = returnValue;
          }
        }
        if (layer.stringValue) {
          for(let i = 0;i<layer.stringValue.length;i++){
            if(item!==guid && layer.setToMode) continue
            const returnValue = LayerVariableManager.instance.getString(item, layer.stringValue[i].varKey)
            layer.stringValue[i].varValue = returnValue;
          }
        }
        if (layer.floatValue) {
          for(let i = 0;i<layer.floatValue.length;i++){
            if(item!==guid && layer.setToMode) continue
            const returnValue = LayerVariableManager.instance.getFloat(item, layer.floatValue[i].varKey)
            layer.floatValue[i].varValue = returnValue;
          }
        }
        if (layer.booleValue) {
          for(let i = 0;i<layer.booleValue.length;i++){
            if(item!==guid && layer.setToMode) continue
            const returnValue = LayerVariableManager.instance.getBoolean(item, layer.booleValue[i].varKey)
            layer.booleValue[i].varValue = returnValue;
          }
        }
      }
    }
    this.variableLayerInfo = JSON.parse(JSON.stringify(this.variableLayerInfo));
  }
  //返回颜色数据
  getColor(guid: string, varKey: string) {
    return this.variableLayerInfo[guid].colorValue?.find(item => item.varKey ===
      varKey)?.varValue as string
  }

  //返回文本数据
  getString(guid: string, varKey: string) {
    return this.variableLayerInfo[guid].stringValue?.find(item => item.varKey ===
      varKey)?.varValue as string
  }

  //返回数字数据
  getFloat(guid: string, varKey: string) {
    return this.variableLayerInfo[guid].floatValue?.find(item => item.varKey ===
      varKey)?.varValue as number
  }

  //返回布尔数据
  getBoolean(guid: string, varKey: string){
    return this.variableLayerInfo[guid].booleValue?.find(item => item.varKey ===
      varKey)?.varValue as boolean
  }
}