import { LayerVariableManager, VariableLayerInfo } from "./LayerVariableManager";

export class LayerVariableInfoManager {
  private static _instance: LayerVariableInfoManager | null = null;

  public variableLayerInfo: VariableLayerInfo = {
  "2:59": {
    "guid": "2:59",
    "childGuids": [
      "2:109",
      "2:110",
      "2:653",
      "2:659",
      "2:661",
      "2:660",
      "2:654",
      "2:655",
      "2:644",
      "2:650",
      "2:652",
      "2:651",
      "2:645",
      "2:646",
      "2:635",
      "2:641",
      "2:643",
      "2:642",
      "2:636",
      "2:637",
      "2:626",
      "2:632",
      "2:634",
      "2:633",
      "2:627",
      "2:628",
      "2:617",
      "2:623",
      "2:625",
      "2:624",
      "2:618",
      "2:619",
      "2:608",
      "2:614",
      "2:616",
      "2:615",
      "2:609",
      "2:610",
      "2:599",
      "2:605",
      "2:607",
      "2:606",
      "2:600",
      "2:601",
      "2:590",
      "2:596",
      "2:598",
      "2:597",
      "2:591",
      "2:592",
      "2:581",
      "2:587",
      "2:589",
      "2:588",
      "2:582",
      "2:583",
      "2:189",
      "2:197",
      "2:198",
      "2:194",
      "2:195",
      "2:190",
      "2:191",
      "2:111",
      "2:130",
      "2:134",
      "2:131",
      "2:116",
      "2:124",
      "2:129",
      "2:125",
      "2:117",
      "2:123",
      "2:118",
      "2:122",
      "2:121",
      "2:120",
      "2:119",
      "2:115",
      "2:112",
      "2:114",
      "2:113",
      "2:662",
      "2:664",
      "2:60",
      "2:93",
      "2:107",
      "2:108",
      "2:100",
      "2:105",
      "2:102",
      "2:104",
      "2:103",
      "2:101",
      "2:99",
      "2:94",
      "2:98",
      "2:95",
      "2:92",
      "2:70",
      "2:72",
      "2:85",
      "2:91",
      "2:86",
      "2:80",
      "2:84",
      "2:81",
      "2:73",
      "2:79",
      "2:74",
      "2:78",
      "2:77",
      "2:76",
      "2:75",
      "2:71",
      "2:61",
      "2:67",
      "2:69",
      "2:68",
      "2:62",
      "2:63"
    ],
    "parentGuids": [
      "0:1"
    ],
    "colorValue": [
      {
        "varKey": "2:35",
        "varValue": "rgba(18, 11, 31, 1)"
      }
    ]
  },
  "2:60": {
    "guid": "2:60",
    "childGuids": [
      "2:93",
      "2:107",
      "2:108",
      "2:100",
      "2:105",
      "2:102",
      "2:104",
      "2:103",
      "2:101",
      "2:99",
      "2:94",
      "2:98",
      "2:95",
      "2:92",
      "2:70",
      "2:72",
      "2:85",
      "2:91",
      "2:86",
      "2:80",
      "2:84",
      "2:81",
      "2:73",
      "2:79",
      "2:74",
      "2:78",
      "2:77",
      "2:76",
      "2:75",
      "2:71",
      "2:61",
      "2:67",
      "2:69",
      "2:68",
      "2:62",
      "2:63"
    ],
    "parentGuids": [
      "0:1",
      "2:59"
    ],
    "colorValue": [
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:62": {
    "guid": "2:62",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:61"
    ],
    "childGuids": [
      "2:63"
    ],
    "floatValue": [
      {
        "varKey": "2:54",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:68": {
    "guid": "2:68",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:61",
      "2:67"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:69": {
    "guid": "2:69",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:61",
      "2:67"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:71": {
    "guid": "2:71",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:70"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:73": {
    "guid": "2:73",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:70",
      "2:72"
    ],
    "childGuids": [
      "2:79",
      "2:74",
      "2:78",
      "2:77",
      "2:76",
      "2:75"
    ],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      }
    ]
  },
  "2:80": {
    "guid": "2:80",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:70",
      "2:72"
    ],
    "childGuids": [
      "2:84",
      "2:81"
    ],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:84": {
    "guid": "2:84",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:70",
      "2:72",
      "2:80"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:85": {
    "guid": "2:85",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:70",
      "2:72"
    ],
    "childGuids": [
      "2:91",
      "2:86"
    ],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:91": {
    "guid": "2:91",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:70",
      "2:72",
      "2:85"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:94": {
    "guid": "2:94",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:93"
    ],
    "childGuids": [
      "2:98",
      "2:95"
    ],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:98": {
    "guid": "2:98",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:93",
      "2:94"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:99": {
    "guid": "2:99",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:93"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      }
    ]
  },
  "2:100": {
    "guid": "2:100",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:93"
    ],
    "childGuids": [
      "2:105",
      "2:102",
      "2:104",
      "2:103",
      "2:101"
    ],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:48",
        "varValue": "rgba(255, 255, 255, 0.039216)"
      }
    ]
  },
  "2:103": {
    "guid": "2:103",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:93",
      "2:100",
      "2:102"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:104": {
    "guid": "2:104",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:93",
      "2:100",
      "2:102"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:108": {
    "guid": "2:108",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:60",
      "2:93",
      "2:107"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:110": {
    "guid": "2:110",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109"
    ],
    "childGuids": [
      "2:653",
      "2:659",
      "2:661",
      "2:660",
      "2:654",
      "2:655",
      "2:644",
      "2:650",
      "2:652",
      "2:651",
      "2:645",
      "2:646",
      "2:635",
      "2:641",
      "2:643",
      "2:642",
      "2:636",
      "2:637",
      "2:626",
      "2:632",
      "2:634",
      "2:633",
      "2:627",
      "2:628",
      "2:617",
      "2:623",
      "2:625",
      "2:624",
      "2:618",
      "2:619",
      "2:608",
      "2:614",
      "2:616",
      "2:615",
      "2:609",
      "2:610",
      "2:599",
      "2:605",
      "2:607",
      "2:606",
      "2:600",
      "2:601",
      "2:590",
      "2:596",
      "2:598",
      "2:597",
      "2:591",
      "2:592",
      "2:581",
      "2:587",
      "2:589",
      "2:588",
      "2:582",
      "2:583",
      "2:189",
      "2:197",
      "2:198",
      "2:194",
      "2:195",
      "2:190",
      "2:191",
      "2:111",
      "2:130",
      "2:134",
      "2:131",
      "2:116",
      "2:124",
      "2:129",
      "2:125",
      "2:117",
      "2:123",
      "2:118",
      "2:122",
      "2:121",
      "2:120",
      "2:119",
      "2:115",
      "2:112",
      "2:114",
      "2:113",
      "2:662",
      "2:664"
    ],
    "floatValue": [
      {
        "varKey": "2:52",
        "varValue": 24
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:37",
        "varValue": "rgba(22, 13, 38, 1)"
      }
    ]
  },
  "2:113": {
    "guid": "2:113",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:111",
      "2:112"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:114": {
    "guid": "2:114",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:111",
      "2:112"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:116": {
    "guid": "2:116",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:111"
    ],
    "childGuids": [
      "2:124",
      "2:129",
      "2:125",
      "2:117",
      "2:123",
      "2:118",
      "2:122",
      "2:121",
      "2:120",
      "2:119"
    ],
    "floatValue": [
      {
        "varKey": "2:53",
        "varValue": 10
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:49",
        "varValue": "rgba(255, 255, 255, 0.058824)"
      }
    ]
  },
  "2:117": {
    "guid": "2:117",
    "childGuids": [
      "2:123",
      "2:118",
      "2:122",
      "2:121",
      "2:120",
      "2:119"
    ],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:111",
      "2:116"
    ],
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      }
    ]
  },
  "2:129": {
    "guid": "2:129",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:111",
      "2:116",
      "2:124"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:130": {
    "guid": "2:130",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:111"
    ],
    "childGuids": [
      "2:134",
      "2:131"
    ],
    "floatValue": [
      {
        "varKey": "2:53",
        "varValue": 10
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      }
    ]
  },
  "2:189": {
    "guid": "2:189",
    "childGuids": [
      "2:197",
      "2:198",
      "2:194",
      "2:195",
      "2:190",
      "2:191"
    ],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:190": {
    "guid": "2:190",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:189"
    ],
    "childGuids": [
      "2:191"
    ],
    "floatValue": [
      {
        "varKey": "2:53",
        "varValue": 10
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:194": {
    "guid": "2:194",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:189"
    ],
    "childGuids": [
      "2:195"
    ],
    "floatValue": [
      {
        "varKey": "2:53",
        "varValue": 10
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:197": {
    "guid": "2:197",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:189"
    ],
    "childGuids": [
      "2:198"
    ],
    "floatValue": [
      {
        "varKey": "2:53",
        "varValue": 10
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:581": {
    "guid": "2:581",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110"
    ],
    "childGuids": [
      "2:587",
      "2:589",
      "2:588",
      "2:582",
      "2:583"
    ],
    "floatValue": [
      {
        "varKey": "2:51",
        "varValue": 18
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:582": {
    "guid": "2:582",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:581"
    ],
    "childGuids": [
      "2:583"
    ],
    "floatValue": [
      {
        "varKey": "2:54",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:588": {
    "guid": "2:588",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:581",
      "2:587"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:589": {
    "guid": "2:589",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:581",
      "2:587"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:590": {
    "guid": "2:590",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110"
    ],
    "childGuids": [
      "2:596",
      "2:598",
      "2:597",
      "2:591",
      "2:592"
    ],
    "floatValue": [
      {
        "varKey": "2:51",
        "varValue": 18
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:591": {
    "guid": "2:591",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:590"
    ],
    "childGuids": [
      "2:592"
    ],
    "floatValue": [
      {
        "varKey": "2:54",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:597": {
    "guid": "2:597",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:590",
      "2:596"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:598": {
    "guid": "2:598",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:590",
      "2:596"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:599": {
    "guid": "2:599",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110"
    ],
    "childGuids": [
      "2:605",
      "2:607",
      "2:606",
      "2:600",
      "2:601"
    ],
    "floatValue": [
      {
        "varKey": "2:51",
        "varValue": 18
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:600": {
    "guid": "2:600",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:599"
    ],
    "childGuids": [
      "2:601"
    ],
    "floatValue": [
      {
        "varKey": "2:54",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:606": {
    "guid": "2:606",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:599",
      "2:605"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:607": {
    "guid": "2:607",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:599",
      "2:605"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:608": {
    "guid": "2:608",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110"
    ],
    "childGuids": [
      "2:614",
      "2:616",
      "2:615",
      "2:609",
      "2:610"
    ],
    "floatValue": [
      {
        "varKey": "2:51",
        "varValue": 18
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:609": {
    "guid": "2:609",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:608"
    ],
    "childGuids": [
      "2:610"
    ],
    "floatValue": [
      {
        "varKey": "2:54",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:615": {
    "guid": "2:615",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:608",
      "2:614"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:616": {
    "guid": "2:616",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:608",
      "2:614"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:617": {
    "guid": "2:617",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110"
    ],
    "childGuids": [
      "2:623",
      "2:625",
      "2:624",
      "2:618",
      "2:619"
    ],
    "floatValue": [
      {
        "varKey": "2:51",
        "varValue": 18
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:618": {
    "guid": "2:618",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:617"
    ],
    "childGuids": [
      "2:619"
    ],
    "floatValue": [
      {
        "varKey": "2:54",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:624": {
    "guid": "2:624",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:617",
      "2:623"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:625": {
    "guid": "2:625",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:617",
      "2:623"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:626": {
    "guid": "2:626",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110"
    ],
    "childGuids": [
      "2:632",
      "2:634",
      "2:633",
      "2:627",
      "2:628"
    ],
    "floatValue": [
      {
        "varKey": "2:51",
        "varValue": 18
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:627": {
    "guid": "2:627",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:626"
    ],
    "childGuids": [
      "2:628"
    ],
    "floatValue": [
      {
        "varKey": "2:54",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:633": {
    "guid": "2:633",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:626",
      "2:632"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:634": {
    "guid": "2:634",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:626",
      "2:632"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:635": {
    "guid": "2:635",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110"
    ],
    "childGuids": [
      "2:641",
      "2:643",
      "2:642",
      "2:636",
      "2:637"
    ],
    "floatValue": [
      {
        "varKey": "2:51",
        "varValue": 18
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:636": {
    "guid": "2:636",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:635"
    ],
    "childGuids": [
      "2:637"
    ],
    "floatValue": [
      {
        "varKey": "2:54",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:642": {
    "guid": "2:642",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:635",
      "2:641"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:643": {
    "guid": "2:643",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:635",
      "2:641"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:644": {
    "guid": "2:644",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110"
    ],
    "childGuids": [
      "2:650",
      "2:652",
      "2:651",
      "2:645",
      "2:646"
    ],
    "floatValue": [
      {
        "varKey": "2:51",
        "varValue": 18
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:645": {
    "guid": "2:645",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:644"
    ],
    "childGuids": [
      "2:646"
    ],
    "floatValue": [
      {
        "varKey": "2:54",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:651": {
    "guid": "2:651",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:644",
      "2:650"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:652": {
    "guid": "2:652",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:644",
      "2:650"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:653": {
    "guid": "2:653",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110"
    ],
    "childGuids": [
      "2:659",
      "2:661",
      "2:660",
      "2:654",
      "2:655"
    ],
    "floatValue": [
      {
        "varKey": "2:51",
        "varValue": 18
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:654": {
    "guid": "2:654",
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:653"
    ],
    "childGuids": [
      "2:655"
    ],
    "floatValue": [
      {
        "varKey": "2:54",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:660": {
    "guid": "2:660",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:653",
      "2:659"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:661": {
    "guid": "2:661",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:59",
      "2:109",
      "2:110",
      "2:653",
      "2:659"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  }
};

  private constructor() {}


  static get instance(): LayerVariableInfoManager {
    if (!LayerVariableInfoManager._instance) {
      LayerVariableInfoManager._instance = new LayerVariableInfoManager();
    }
    return LayerVariableInfoManager._instance;
  }
  // 更新当前图层的模式设置
  // 更新后需要循环更新当前图层下子图层所有的变量模式
  updateSetToMode(guid: string, setId: string, modeId: string) {
    const variableLayer = this.variableLayerInfo[guid];
    if (!variableLayer) {
      return;
    }
    variableLayer.setToMode = {};
    variableLayer.setToMode[setId] = modeId;
    //开始更新所有包含子图层的数据信息
    const guids = [guid, ...variableLayer.childGuids];
    for (let item of guids) {
      const layer = this.variableLayerInfo[item];
      if (layer) {
        if (layer.colorValue) {
          for(let i = 0;i<layer.colorValue.length;i++){
            if(item!==guid && layer.setToMode) continue
            const returnValue = LayerVariableManager.instance.getColor(item, layer.colorValue[i].varKey)
            layer.colorValue[i].varValue = returnValue;
          }
        }
        if (layer.stringValue) {
          for(let i = 0;i<layer.stringValue.length;i++){
            if(item!==guid && layer.setToMode) continue
            const returnValue = LayerVariableManager.instance.getString(item, layer.stringValue[i].varKey)
            layer.stringValue[i].varValue = returnValue;
          }
        }
        if (layer.floatValue) {
          for(let i = 0;i<layer.floatValue.length;i++){
            if(item!==guid && layer.setToMode) continue
            const returnValue = LayerVariableManager.instance.getFloat(item, layer.floatValue[i].varKey)
            layer.floatValue[i].varValue = returnValue;
          }
        }
        if (layer.booleValue) {
          for(let i = 0;i<layer.booleValue.length;i++){
            if(item!==guid && layer.setToMode) continue
            const returnValue = LayerVariableManager.instance.getBoolean(item, layer.booleValue[i].varKey)
            layer.booleValue[i].varValue = returnValue;
          }
        }
      }
    }
    this.variableLayerInfo = JSON.parse(JSON.stringify(this.variableLayerInfo));
  }
  //返回颜色数据
  getColor(guid: string, varKey: string) {
    return this.variableLayerInfo[guid].colorValue?.find(item => item.varKey ===
      varKey)?.varValue as string
  }

  //返回文本数据
  getString(guid: string, varKey: string) {
    return this.variableLayerInfo[guid].stringValue?.find(item => item.varKey ===
      varKey)?.varValue as string
  }

  //返回数字数据
  getFloat(guid: string, varKey: string) {
    return this.variableLayerInfo[guid].floatValue?.find(item => item.varKey ===
      varKey)?.varValue as number
  }

  //返回布尔数据
  getBoolean(guid: string, varKey: string){
    return this.variableLayerInfo[guid].booleValue?.find(item => item.varKey ===
      varKey)?.varValue as boolean
  }
}