import { LayerVariableManager, VariableLayerInfo } from "./LayerVariableManager";

export class LayerVariableInfoManager {
  private static _instance: LayerVariableInfoManager | null = null;

  public variableLayerInfo: VariableLayerInfo = {
  "2:367": {
    "guid": "2:367",
    "childGuids": [
      "2:535",
      "2:512",
      "2:558",
      "2:574",
      "2:579",
      "2:578",
      "2:577",
      "2:576",
      "2:575",
      "2:569",
      "2:573",
      "2:572",
      "2:571",
      "2:570",
      "2:564",
      "2:568",
      "2:567",
      "2:566",
      "2:565",
      "2:559",
      "2:563",
      "2:562",
      "2:561",
      "2:560",
      "2:514",
      "2:530",
      "2:534",
      "2:531",
      "2:533",
      "2:532",
      "2:525",
      "2:529",
      "2:526",
      "2:528",
      "2:527",
      "2:520",
      "2:524",
      "2:521",
      "2:523",
      "2:522",
      "2:515",
      "2:519",
      "2:516",
      "2:518",
      "2:517",
      "2:513",
      "2:491",
      "2:493",
      "2:509",
      "2:511",
      "2:510",
      "2:506",
      "2:508",
      "2:507",
      "2:503",
      "2:505",
      "2:504",
      "2:500",
      "2:502",
      "2:501",
      "2:497",
      "2:499",
      "2:498",
      "2:494",
      "2:496",
      "2:495",
      "2:492",
      "2:476",
      "2:478",
      "2:488",
      "2:490",
      "2:489",
      "2:485",
      "2:487",
      "2:486",
      "2:482",
      "2:484",
      "2:483",
      "2:479",
      "2:481",
      "2:480",
      "2:477",
      "2:436",
      "2:459",
      "2:472",
      "2:475",
      "2:474",
      "2:473",
      "2:468",
      "2:471",
      "2:470",
      "2:469",
      "2:464",
      "2:467",
      "2:466",
      "2:465",
      "2:460",
      "2:463",
      "2:462",
      "2:461",
      "2:438",
      "2:455",
      "2:458",
      "2:457",
      "2:456",
      "2:451",
      "2:454",
      "2:453",
      "2:452",
      "2:447",
      "2:450",
      "2:449",
      "2:448",
      "2:443",
      "2:446",
      "2:445",
      "2:444",
      "2:439",
      "2:442",
      "2:441",
      "2:440",
      "2:437",
      "2:371",
      "2:399",
      "2:424",
      "2:426",
      "2:434",
      "2:431",
      "2:433",
      "2:432",
      "2:427",
      "2:428",
      "2:425",
      "2:411",
      "2:413",
      "2:422",
      "2:419",
      "2:421",
      "2:420",
      "2:414",
      "2:415",
      "2:412",
      "2:400",
      "2:402",
      "2:408",
      "2:410",
      "2:409",
      "2:403",
      "2:404",
      "2:401",
      "2:373",
      "2:390",
      "2:392",
      "2:397",
      "2:394",
      "2:396",
      "2:395",
      "2:393",
      "2:391",
      "2:381",
      "2:383",
      "2:389",
      "2:384",
      "2:388",
      "2:387",
      "2:386",
      "2:385",
      "2:382",
      "2:374",
      "2:376",
      "2:380",
      "2:377",
      "2:375",
      "2:372",
      "2:368",
      "2:370",
      "2:369"
    ],
    "parentGuids": [
      "0:1"
    ],
    "colorValue": [
      {
        "varKey": "2:35",
        "varValue": "rgba(18, 11, 31, 1)"
      }
    ]
  },
  "2:369": {
    "guid": "2:369",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:368"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:370": {
    "guid": "2:370",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:368"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:372": {
    "guid": "2:372",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:374": {
    "guid": "2:374",
    "childGuids": [
      "2:376",
      "2:380",
      "2:377",
      "2:375"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:373"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:375": {
    "guid": "2:375",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:373",
      "2:374"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:376": {
    "guid": "2:376",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:373",
      "2:374"
    ],
    "childGuids": [
      "2:380",
      "2:377"
    ],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:380": {
    "guid": "2:380",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:373",
      "2:374",
      "2:376"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:381": {
    "guid": "2:381",
    "childGuids": [
      "2:383",
      "2:389",
      "2:384",
      "2:388",
      "2:387",
      "2:386",
      "2:385",
      "2:382"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:373"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:382": {
    "guid": "2:382",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:373",
      "2:381"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:383": {
    "guid": "2:383",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:373",
      "2:381"
    ],
    "childGuids": [
      "2:389",
      "2:384",
      "2:388",
      "2:387",
      "2:386",
      "2:385"
    ],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      }
    ]
  },
  "2:390": {
    "guid": "2:390",
    "childGuids": [
      "2:392",
      "2:397",
      "2:394",
      "2:396",
      "2:395",
      "2:393",
      "2:391"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:373"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:391": {
    "guid": "2:391",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:373",
      "2:390"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:392": {
    "guid": "2:392",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:373",
      "2:390"
    ],
    "childGuids": [
      "2:397",
      "2:394",
      "2:396",
      "2:395",
      "2:393"
    ],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:48",
        "varValue": "rgba(255, 255, 255, 0.039216)"
      }
    ]
  },
  "2:395": {
    "guid": "2:395",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:373",
      "2:390",
      "2:392",
      "2:394"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:396": {
    "guid": "2:396",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:373",
      "2:390",
      "2:392",
      "2:394"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:400": {
    "guid": "2:400",
    "childGuids": [
      "2:402",
      "2:408",
      "2:410",
      "2:409",
      "2:403",
      "2:404",
      "2:401"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:401": {
    "guid": "2:401",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:400"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:402": {
    "guid": "2:402",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:400"
    ],
    "childGuids": [
      "2:408",
      "2:410",
      "2:409",
      "2:403",
      "2:404"
    ],
    "floatValue": [
      {
        "varKey": "2:51",
        "varValue": 18
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:403": {
    "guid": "2:403",
    "childGuids": [
      "2:404"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:400",
      "2:402"
    ],
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:409": {
    "guid": "2:409",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:400",
      "2:402",
      "2:408"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:410": {
    "guid": "2:410",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:400",
      "2:402",
      "2:408"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:411": {
    "guid": "2:411",
    "childGuids": [
      "2:413",
      "2:422",
      "2:419",
      "2:421",
      "2:420",
      "2:414",
      "2:415",
      "2:412"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:412": {
    "guid": "2:412",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:411"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:413": {
    "guid": "2:413",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:411"
    ],
    "childGuids": [
      "2:422",
      "2:419",
      "2:421",
      "2:420",
      "2:414",
      "2:415"
    ],
    "floatValue": [
      {
        "varKey": "2:51",
        "varValue": 18
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:46",
        "varValue": "rgba(124, 77, 255, 0.4)"
      },
      {
        "varKey": "2:39",
        "varValue": "rgba(44, 27, 77, 1)"
      }
    ]
  },
  "2:414": {
    "guid": "2:414",
    "childGuids": [
      "2:415"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:411",
      "2:413"
    ],
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      },
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:420": {
    "guid": "2:420",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:411",
      "2:413",
      "2:419"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:421": {
    "guid": "2:421",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:411",
      "2:413",
      "2:419"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:424": {
    "guid": "2:424",
    "childGuids": [
      "2:426",
      "2:434",
      "2:431",
      "2:433",
      "2:432",
      "2:427",
      "2:428",
      "2:425"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:425": {
    "guid": "2:425",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:424"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:426": {
    "guid": "2:426",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:424"
    ],
    "childGuids": [
      "2:434",
      "2:431",
      "2:433",
      "2:432",
      "2:427",
      "2:428"
    ],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:48",
        "varValue": "rgba(255, 255, 255, 0.039216)"
      }
    ]
  },
  "2:427": {
    "guid": "2:427",
    "childGuids": [
      "2:428"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:424",
      "2:426"
    ],
    "colorValue": [
      {
        "varKey": "2:46",
        "varValue": "rgba(124, 77, 255, 0.4)"
      },
      {
        "varKey": "2:39",
        "varValue": "rgba(44, 27, 77, 1)"
      }
    ]
  },
  "2:432": {
    "guid": "2:432",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:424",
      "2:426",
      "2:431"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:433": {
    "guid": "2:433",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:371",
      "2:399",
      "2:424",
      "2:426",
      "2:431"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:437": {
    "guid": "2:437",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:439": {
    "guid": "2:439",
    "childGuids": [
      "2:442",
      "2:441",
      "2:440"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:440": {
    "guid": "2:440",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:439"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:35",
        "varValue": "rgba(18, 11, 31, 1)"
      }
    ]
  },
  "2:441": {
    "guid": "2:441",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:439"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:442": {
    "guid": "2:442",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:439"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:443": {
    "guid": "2:443",
    "childGuids": [
      "2:446",
      "2:445",
      "2:444"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:444": {
    "guid": "2:444",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:443"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:445": {
    "guid": "2:445",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:443"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:446": {
    "guid": "2:446",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:443"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:447": {
    "guid": "2:447",
    "childGuids": [
      "2:450",
      "2:449",
      "2:448"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:448": {
    "guid": "2:448",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:447"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:37",
        "varValue": "rgba(22, 13, 38, 1)"
      }
    ]
  },
  "2:449": {
    "guid": "2:449",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:447"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:450": {
    "guid": "2:450",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:447"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:451": {
    "guid": "2:451",
    "childGuids": [
      "2:454",
      "2:453",
      "2:452"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:452": {
    "guid": "2:452",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:451"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:453": {
    "guid": "2:453",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:451"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:454": {
    "guid": "2:454",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:451"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:455": {
    "guid": "2:455",
    "childGuids": [
      "2:458",
      "2:457",
      "2:456"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:456": {
    "guid": "2:456",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:455"
    ],
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      }
    ]
  },
  "2:457": {
    "guid": "2:457",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:455"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:458": {
    "guid": "2:458",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:438",
      "2:455"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:460": {
    "guid": "2:460",
    "childGuids": [
      "2:463",
      "2:462",
      "2:461"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:461": {
    "guid": "2:461",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459",
      "2:460"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:462": {
    "guid": "2:462",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459",
      "2:460"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:463": {
    "guid": "2:463",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459",
      "2:460"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:464": {
    "guid": "2:464",
    "childGuids": [
      "2:467",
      "2:466",
      "2:465"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:465": {
    "guid": "2:465",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459",
      "2:464"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:466": {
    "guid": "2:466",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459",
      "2:464"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:467": {
    "guid": "2:467",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459",
      "2:464"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:468": {
    "guid": "2:468",
    "childGuids": [
      "2:471",
      "2:470",
      "2:469"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:469": {
    "guid": "2:469",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459",
      "2:468"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:470": {
    "guid": "2:470",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459",
      "2:468"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:471": {
    "guid": "2:471",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459",
      "2:468"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:472": {
    "guid": "2:472",
    "childGuids": [
      "2:475",
      "2:474",
      "2:473"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:473": {
    "guid": "2:473",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459",
      "2:472"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:474": {
    "guid": "2:474",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459",
      "2:472"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:475": {
    "guid": "2:475",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:436",
      "2:459",
      "2:472"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:477": {
    "guid": "2:477",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:476"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:479": {
    "guid": "2:479",
    "childGuids": [
      "2:481",
      "2:480"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:476",
      "2:478"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:480": {
    "guid": "2:480",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:476",
      "2:478",
      "2:479"
    ],
    "childGuids": [],
    "floatValue": [
      {
        "varKey": "2:50",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:46",
        "varValue": "rgba(124, 77, 255, 0.4)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:481": {
    "guid": "2:481",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:476",
      "2:478",
      "2:479"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:482": {
    "guid": "2:482",
    "childGuids": [
      "2:484",
      "2:483"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:476",
      "2:478"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:483": {
    "guid": "2:483",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:476",
      "2:478",
      "2:482"
    ],
    "childGuids": [],
    "floatValue": [
      {
        "varKey": "2:51",
        "varValue": 18
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:46",
        "varValue": "rgba(124, 77, 255, 0.4)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:484": {
    "guid": "2:484",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:476",
      "2:478",
      "2:482"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:485": {
    "guid": "2:485",
    "childGuids": [
      "2:487",
      "2:486"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:476",
      "2:478"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:486": {
    "guid": "2:486",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:476",
      "2:478",
      "2:485"
    ],
    "childGuids": [],
    "floatValue": [
      {
        "varKey": "2:52",
        "varValue": 24
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:46",
        "varValue": "rgba(124, 77, 255, 0.4)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:487": {
    "guid": "2:487",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:476",
      "2:478",
      "2:485"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:488": {
    "guid": "2:488",
    "childGuids": [
      "2:490",
      "2:489"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:476",
      "2:478"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:489": {
    "guid": "2:489",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:476",
      "2:478",
      "2:488"
    ],
    "childGuids": [],
    "floatValue": [
      {
        "varKey": "2:53",
        "varValue": 10
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    },
    "colorValue": [
      {
        "varKey": "2:46",
        "varValue": "rgba(124, 77, 255, 0.4)"
      },
      {
        "varKey": "2:38",
        "varValue": "rgba(36, 22, 64, 1)"
      }
    ]
  },
  "2:490": {
    "guid": "2:490",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:476",
      "2:478",
      "2:488"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:492": {
    "guid": "2:492",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:494": {
    "guid": "2:494",
    "childGuids": [
      "2:496",
      "2:495"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:495": {
    "guid": "2:495",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493",
      "2:494"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:496": {
    "guid": "2:496",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493",
      "2:494"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:497": {
    "guid": "2:497",
    "childGuids": [
      "2:499",
      "2:498"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:498": {
    "guid": "2:498",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493",
      "2:497"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:499": {
    "guid": "2:499",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493",
      "2:497"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:500": {
    "guid": "2:500",
    "childGuids": [
      "2:502",
      "2:501"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:501": {
    "guid": "2:501",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493",
      "2:500"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:502": {
    "guid": "2:502",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493",
      "2:500"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:503": {
    "guid": "2:503",
    "childGuids": [
      "2:505",
      "2:504"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:504": {
    "guid": "2:504",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493",
      "2:503"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:505": {
    "guid": "2:505",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493",
      "2:503"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:506": {
    "guid": "2:506",
    "childGuids": [
      "2:508",
      "2:507"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:507": {
    "guid": "2:507",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493",
      "2:506"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:508": {
    "guid": "2:508",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493",
      "2:506"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:509": {
    "guid": "2:509",
    "childGuids": [
      "2:511",
      "2:510"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:510": {
    "guid": "2:510",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493",
      "2:509"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:511": {
    "guid": "2:511",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:491",
      "2:493",
      "2:509"
    ],
    "colorValue": [
      {
        "varKey": "2:44",
        "varValue": "rgba(255, 255, 255, 0.4)"
      }
    ]
  },
  "2:513": {
    "guid": "2:513",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:515": {
    "guid": "2:515",
    "childGuids": [
      "2:519",
      "2:516",
      "2:518",
      "2:517"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:516": {
    "guid": "2:516",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:515"
    ],
    "childGuids": [
      "2:518",
      "2:517"
    ],
    "floatValue": [
      {
        "varKey": "2:55",
        "varValue": 8
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:517": {
    "guid": "2:517",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:515",
      "2:516"
    ],
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      }
    ]
  },
  "2:518": {
    "guid": "2:518",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:515",
      "2:516"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:519": {
    "guid": "2:519",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:515"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:520": {
    "guid": "2:520",
    "childGuids": [
      "2:524",
      "2:521",
      "2:523",
      "2:522"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:521": {
    "guid": "2:521",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:520"
    ],
    "childGuids": [
      "2:523",
      "2:522"
    ],
    "floatValue": [
      {
        "varKey": "2:56",
        "varValue": 12
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:522": {
    "guid": "2:522",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:520",
      "2:521"
    ],
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      }
    ]
  },
  "2:523": {
    "guid": "2:523",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:520",
      "2:521"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:524": {
    "guid": "2:524",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:520"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:525": {
    "guid": "2:525",
    "childGuids": [
      "2:529",
      "2:526",
      "2:528",
      "2:527"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:526": {
    "guid": "2:526",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:525"
    ],
    "childGuids": [
      "2:528",
      "2:527"
    ],
    "floatValue": [
      {
        "varKey": "2:57",
        "varValue": 16
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:527": {
    "guid": "2:527",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:525",
      "2:526"
    ],
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      }
    ]
  },
  "2:528": {
    "guid": "2:528",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:525",
      "2:526"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:529": {
    "guid": "2:529",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:525"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:530": {
    "guid": "2:530",
    "childGuids": [
      "2:534",
      "2:531",
      "2:533",
      "2:532"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514"
    ],
    "colorValue": [
      {
        "varKey": "2:45",
        "varValue": "rgba(255, 255, 255, 0.078431)"
      },
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:531": {
    "guid": "2:531",
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:530"
    ],
    "childGuids": [
      "2:533",
      "2:532"
    ],
    "floatValue": [
      {
        "varKey": "2:58",
        "varValue": 24
      }
    ],
    "setToMode": {
      "2:4": "2:3"
    }
  },
  "2:532": {
    "guid": "2:532",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:530",
      "2:531"
    ],
    "colorValue": [
      {
        "varKey": "2:40",
        "varValue": "rgba(124, 77, 255, 1)"
      }
    ]
  },
  "2:533": {
    "guid": "2:533",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:530",
      "2:531"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:534": {
    "guid": "2:534",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:514",
      "2:530"
    ],
    "colorValue": [
      {
        "varKey": "2:43",
        "varValue": "rgba(255, 255, 255, 0.65098)"
      }
    ]
  },
  "2:559": {
    "guid": "2:559",
    "childGuids": [
      "2:563",
      "2:562",
      "2:561",
      "2:560"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558"
    ],
    "colorValue": [
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:560": {
    "guid": "2:560",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:559"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:561": {
    "guid": "2:561",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:559"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:562": {
    "guid": "2:562",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:559"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:563": {
    "guid": "2:563",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:559"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:564": {
    "guid": "2:564",
    "childGuids": [
      "2:568",
      "2:567",
      "2:566",
      "2:565"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558"
    ],
    "colorValue": [
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:565": {
    "guid": "2:565",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:564"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:566": {
    "guid": "2:566",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:564"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:567": {
    "guid": "2:567",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:564"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:568": {
    "guid": "2:568",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:564"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:569": {
    "guid": "2:569",
    "childGuids": [
      "2:573",
      "2:572",
      "2:571",
      "2:570"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558"
    ],
    "colorValue": [
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:570": {
    "guid": "2:570",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:569"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:571": {
    "guid": "2:571",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:569"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:572": {
    "guid": "2:572",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:569"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:573": {
    "guid": "2:573",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:569"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:574": {
    "guid": "2:574",
    "childGuids": [
      "2:579",
      "2:578",
      "2:577",
      "2:576",
      "2:575"
    ],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558"
    ],
    "colorValue": [
      {
        "varKey": "2:36",
        "varValue": "rgba(26, 16, 48, 1)"
      }
    ]
  },
  "2:575": {
    "guid": "2:575",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:574"
    ],
    "colorValue": [
      {
        "varKey": "2:41",
        "varValue": "rgba(167, 139, 250, 1)"
      }
    ]
  },
  "2:576": {
    "guid": "2:576",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:574"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:577": {
    "guid": "2:577",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:574"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:578": {
    "guid": "2:578",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:574"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  },
  "2:579": {
    "guid": "2:579",
    "childGuids": [],
    "parentGuids": [
      "0:1",
      "2:367",
      "2:512",
      "2:558",
      "2:574"
    ],
    "colorValue": [
      {
        "varKey": "2:42",
        "varValue": "rgba(255, 255, 255, 1)"
      }
    ]
  }
};

  private constructor() {}


  static get instance(): LayerVariableInfoManager {
    if (!LayerVariableInfoManager._instance) {
      LayerVariableInfoManager._instance = new LayerVariableInfoManager();
    }
    return LayerVariableInfoManager._instance;
  }
  // 更新当前图层的模式设置
  // 更新后需要循环更新当前图层下子图层所有的变量模式
  updateSetToMode(guid: string, setId: string, modeId: string) {
    const variableLayer = this.variableLayerInfo[guid];
    if (!variableLayer) {
      return;
    }
    variableLayer.setToMode = {};
    variableLayer.setToMode[setId] = modeId;
    //开始更新所有包含子图层的数据信息
    const guids = [guid, ...variableLayer.childGuids];
    for (let item of guids) {
      const layer = this.variableLayerInfo[item];
      if (layer) {
        if (layer.colorValue) {
          for(let i = 0;i<layer.colorValue.length;i++){
            if(item!==guid && layer.setToMode) continue
            const returnValue = LayerVariableManager.instance.getColor(item, layer.colorValue[i].varKey)
            layer.colorValue[i].varValue = returnValue;
          }
        }
        if (layer.stringValue) {
          for(let i = 0;i<layer.stringValue.length;i++){
            if(item!==guid && layer.setToMode) continue
            const returnValue = LayerVariableManager.instance.getString(item, layer.stringValue[i].varKey)
            layer.stringValue[i].varValue = returnValue;
          }
        }
        if (layer.floatValue) {
          for(let i = 0;i<layer.floatValue.length;i++){
            if(item!==guid && layer.setToMode) continue
            const returnValue = LayerVariableManager.instance.getFloat(item, layer.floatValue[i].varKey)
            layer.floatValue[i].varValue = returnValue;
          }
        }
        if (layer.booleValue) {
          for(let i = 0;i<layer.booleValue.length;i++){
            if(item!==guid && layer.setToMode) continue
            const returnValue = LayerVariableManager.instance.getBoolean(item, layer.booleValue[i].varKey)
            layer.booleValue[i].varValue = returnValue;
          }
        }
      }
    }
    this.variableLayerInfo = JSON.parse(JSON.stringify(this.variableLayerInfo));
  }
  //返回颜色数据
  getColor(guid: string, varKey: string) {
    return this.variableLayerInfo[guid].colorValue?.find(item => item.varKey ===
      varKey)?.varValue as string
  }

  //返回文本数据
  getString(guid: string, varKey: string) {
    return this.variableLayerInfo[guid].stringValue?.find(item => item.varKey ===
      varKey)?.varValue as string
  }

  //返回数字数据
  getFloat(guid: string, varKey: string) {
    return this.variableLayerInfo[guid].floatValue?.find(item => item.varKey ===
      varKey)?.varValue as number
  }

  //返回布尔数据
  getBoolean(guid: string, varKey: string){
    return this.variableLayerInfo[guid].booleValue?.find(item => item.varKey ===
      varKey)?.varValue as boolean
  }
}